# Database configuration

# MongoDB connection string
mongo="mongodb://127.0.0.1:27017/zone-mta"

# Redis connection string
redis="redis://localhost:6379/2"

# Database name for ZoneMTA data in MongoDB. In most cases it should be the same as in the connection string
sender="zone-mta"
