# Database configuration

mongo = "mongodb://127.0.0.1:27017/wildduck"
gridfs = "attachments"
users = "users"
sender = "zonemta"

# Redis connection information
[redis]
host = "localhost"
port = 6379
db = 3
